### ISSUE TITLE
Module matchering not found

### ISSUE THREAD

**Issue by rcrath** [sergree/matchering-cli#2]
I have a hunch I am missing something obvious, but I don't know what it is.

Steps to reproduce:

* Install matchering via docker on linux, 
* start docker 
* start matchering container
* run matchering.web successfully, getting 24 bit result
* run command 
```
`python3 mg_cli.py "/home/rich/bin/matchering-cli/target/Water Brush mhs 86 BPM 3.wav"  "/home/rich/bin/matchering-cli/reference/01 - So What.flac" "/home/rich/bin/matchering-cli/output/Water Brush mhs 86 BPM 3 (so WHat).wav" --log process.log -b32 --no_limiter --dont_normalize
``` 
and receive vollowing error 

```
Traceback (most recent call last):
  File "/home/rich/bin/matchering-cli/mg_cli.py", line 14, in <module>
    import matchering as mg
ModuleNotFoundError: No module named 'matchering'
```

**Comment by sergree** [comment]
Hello @rcrath, nice to meet you again! 

I think Docker container's environment is not related to your linux distro's environment. They are completely separate.

Try to follow these installation steps, please, to install Matchering without Docker:
https://github.com/sergree/matchering-cli#installation

**Comment by rcrath** [comment]
Got CLI running by following yr instructions. got an error that i fixed by downgrading llvm from v. 11 to v. 10. Could you update to include a greater than 9 instead of going by single versions (9,10,...?). hmmm, it might be a requirement of one of the depenencies, not you though. Thanks for the help! I forget why I have the docker version running, I think it runs with the web version. I guess I can take that out unless the web version is supporting 32 bit yet.
